stages:
  - test

variables:
  # Go
  GO_IMAGE: golang:latest

####################################################################################################
## Test
####################################################################################################

test:
  stage: test
  image: $GO_IMAGE
  tags:
    - docker
  script:
    - apt update && install -y dbus-x11
    - go test ./...
