stages:
  - test

variables:
  # Go
  GO_IMAGE: golang:latest

####################################################################################################
## Test
####################################################################################################

test:
  stage: test
  image: $GO_IMAGE
  tags:
    - docker
  script:
    - apt update && apt install -y dbus-x11 gnome-keyring
    - make test
