name: CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install go
        uses: actions/setup-go@v2
        with:
          go-version: '^1.15.2'

      - name: Install system dependencies
        run: |
              sudo apt update && sudo apt install -y dbus-x11 gnome-keyring libsecret-1-0 python-keyring
              dbus-launch /usr/bin/python -c "import keyring;keyring.set_password('system', 'login', '');"

      - name: Go test
        run: make test
