name: CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install go
        uses: actions/setup-go@v2
        with:
          go-version: '^1.15.2'

      - name: Install system dependencies
        run: |
              sudo apt update && sudo apt install -y dbus-x11 gnome-keyring libsecret-1-0 python-keyring
              sudo dbus-run-session -- sh
              sudo echo password | sudo gnome-keyring-daemon --unlock
              # sudo dbus-launch /usr/bin/python -c "import keyring;keyring.get_keyring();keyring.set_password('default', 'login', 'password');"
              #/usr/bin/gnome-keyring-daemon --start --components=secrets,ssh


      - name: Go test
        run: make test
